/* Panel Pustaka (video & pedoman) */
const pst=document.createElement('style');
pst.textContent=`#pk{position:fixed;inset:auto 14px 70px auto;width:min(520px,calc(100% - 28px));height:min(78vh,620px);z-index:99999;background:var(--pkbg);color:var(--pkfg);border:1px solid #8886;border-radius:14px;display:none;flex-direction:column;box-shadow:0 8px 30px #0005;font:14px/1.45 system-ui,sans-serif}
#pk header{display:flex;align-items:center;gap:8px;padding:10px 14px;border-bottom:1px solid #8884;font-weight:600;position:static;background:none}#pk header span{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
#pk button{font:inherit;cursor:pointer;color:inherit}#pk .x{background:none;border:0;font-size:18px;line-height:1;padding:3px 6px;border-radius:8px}#pk .x:hover{background:#8882}
#pk nav{display:flex;flex-wrap:wrap;gap:6px;padding:8px 14px;flex:none;overflow:visible}
#pk nav button{flex:none;white-space:nowrap;padding:5px 12px;border-radius:999px;border:1px solid #8886;background:transparent;font-size:13px;transition:background .15s,border-color .15s}
#pk nav button.on{background:#1f6b4a;color:#fff;border-color:#1f6b4a}
#pkb{flex:1;overflow-y:auto;overflow-x:hidden;padding:6px 10px 16px 14px;scrollbar-gutter:stable;scrollbar-width:thin}#pkb::-webkit-scrollbar{width:8px}#pkb::-webkit-scrollbar-thumb{background:#8887;border-radius:999px}#pkb::-webkit-scrollbar-thumb:hover{background:#8889}
.vc{margin:0 0 12px;border:1px solid #8884;border-radius:10px;overflow:hidden}.vc .th{position:relative;aspect-ratio:16/9;background:#000 center/cover;cursor:pointer;display:grid;place-items:center}
.vc .th b{width:52px;height:52px;border-radius:50%;background:#000a;color:#fff;display:grid;place-items:center;font-size:20px}.vc iframe{width:100%;aspect-ratio:16/9;border:0;display:block}
.vc p{margin:0;padding:8px 10px;font-size:13px}.vc a{color:inherit;opacity:.75;font-size:12px;padding:0 10px 8px;display:inline-block}
.pi{border:1px solid #8884;border-radius:10px;padding:10px 12px;margin:0 0 10px;line-height:1.5}.pi small{opacity:.7;display:block}
.pi .bd{display:inline-block;font-size:11px;padding:2px 9px;border-radius:999px;margin:0 6px 4px 0;background:#ff9f1c33;border:1px solid #ff9f1c88;line-height:1.6}
.pi .pn{color:#1f6b4a}.pi .pt{font-weight:600;margin:2px 0 8px}.pi .mr{display:flex;gap:8px;font-size:13px;padding:2px 0;border-top:1px dashed #8883}.pi .mr span{flex:none;width:104px;opacity:.65}.pi .mr b{font-weight:600}.pi .kt{font-size:12px;opacity:.65;margin:8px 0 2px}.pi .kd{font-size:13.5px;line-height:1.55}.pi .pv{margin-top:10px;width:100%;padding:8px 10px;border-radius:9px;border:1px solid #1f6b4a;background:transparent;font-size:13px;font-weight:600}.pi .pv:hover{background:#1f6b4a22}.pi .pw{display:none;margin-top:8px}.pi .pw iframe{width:100%;height:440px;border:1px solid #8884;border-radius:8px;background:#fff}.pi .pf{font-size:12px;opacity:.75;margin-top:4px}.pi .sm{margin-top:9px;padding-top:6px;border-top:1px solid #8883;font-size:11px;opacity:.6;overflow-wrap:anywhere}.pi .sm a{display:inline;margin:0;font-size:11px;color:inherit}#pk input{width:100%;font:inherit;padding:8px 10px;border-radius:9px;border:1px solid #8886;background:transparent;color:inherit;margin:4px 0 8px}`;
document.head.appendChild(pst);
const pk=document.createElement('div');pk.id='pk';
pk.innerHTML='<header><span>📚 Video & Pedoman Bina Marga</span><button class="x">✕</button></header><nav></nav><div id="pkb"></div>';
document.body.appendChild(pk);
let tab='v',flt='all',qy='';
const TABS=[['v','🎬 Video'],['all','Pedoman: semua'],['new','Belum ada di dokumen'],['J','Jembatan'],['R','Jalan'],['N','SE / Permen']];
function vcard(src,title,link,ratio){const d=document.createElement('div');d.className='vc';
  d.innerHTML=`<div class="th" style="background-image:url(${ratio?'':`https://img.youtube.com/vi/${src}/mqdefault.jpg`})"><b>▶</b></div><p>${esc(title)}</p><a href="${link}" target="_blank" rel="noopener noreferrer">Buka di YouTube ↗</a>`;
  d.querySelector('.th').onclick=e=>{if(location.protocol==='file:'){const n=document.createElement('div');n.style.cssText='padding:14px;font-size:13px;background:#ff9f1c22';n.textContent='Pemutar video di dalam aplikasi butuh alamat web (https). File ini sedang dibuka langsung dari komputer, jadi YouTube menolak memutar (galat 153). Setelah dipasang di GitHub Pages, video langsung diputar di sini.';e.currentTarget.replaceWith(n);return}const f=document.createElement('iframe');f.allowFullscreen=true;f.allow='autoplay; encrypted-media; picture-in-picture';f.referrerPolicy='strict-origin-when-cross-origin';f.title=title;
    f.src=ratio?`https://www.youtube-nocookie.com/embed/videoseries?list=${src}&playsinline=1&origin=${encodeURIComponent(location.origin)}`:`https://www.youtube-nocookie.com/embed/${src}?autoplay=1&rel=0&playsinline=1&origin=${encodeURIComponent(location.origin)}`;e.currentTarget.replaceWith(f)};return d}
function drawPk(){const nav=pk.querySelector('nav'),b=pk.querySelector('#pkb');nav.innerHTML='';
  TABS.forEach(([k,l])=>{const x=document.createElement('button');x.textContent=l;if(k===tab)x.className='on';x.onclick=()=>{tab=k;drawPk()};nav.appendChild(x)});
  b.innerHTML='';
  if(tab==='v'){const n=document.createElement('p');n.style.opacity='.75';n.textContent='Video resmi dari situs Ditjen Bina Marga dan kanal YouTube resmi. Klik untuk memutar.';b.appendChild(n);
    CHN.forEach(c=>b.appendChild(vcard(c[0],c[1],c[2],true)));VID.forEach(v=>b.appendChild(vcard(v[0],v[1],'https://www.youtube.com/watch?v='+v[0])));return}
  const i=document.createElement('input');i.placeholder='Cari pedoman...';i.value=qy;b.appendChild(i);
  const box=document.createElement('div');b.appendChild(box);box.onclick=e=>{const t=e.target.closest('.pv');if(!t)return;const w=t.nextElementSibling,s=t.dataset.src;if(w.style.display==='block'){w.style.display='none';w.innerHTML='';t.textContent='📄 Pratinjau isi dokumen';return}
    w.style.display='block';const g='https://docs.google.com/gview?embedded=true&url='+encodeURIComponent(s);w.innerHTML='<iframe src="'+g+'"></iframe><div class="pf">Pratinjau dimuat lewat penampil Google, tunggu beberapa detik. Kosong atau gagal? <a target="_blank" rel="noopener noreferrer" href="'+s+'">Buka PDF di tab baru</a> · <a target="_blank" rel="noopener noreferrer" href="'+g.replace('embedded=true&','')+'">Buka di penampil Google</a></div>';t.textContent='✕ Tutup pratinjau'};
  const list=()=>{qy=i.value;const w=qy.toLowerCase().split(/\s+/).filter(Boolean);
    const L=PK.filter(p=>(tab==='all'||(tab==='new'?!p.a:p.k===tab))&&w.every(x=>(p.no+' '+p.t+' '+p.d).toLowerCase().includes(x)));
    box.innerHTML=`<p style="opacity:.7;margin:0 0 8px">${L.length} pedoman</p>`+L.map(p=>{const r=(a,b)=>b?`<div class="mr"><span>${a}</span><b>${esc(String(b))}</b></div>`:'';
      return `<div class="pi"><b class="pn">${esc(p.no)}</b> · ${p.y}<div class="pt">${esc(p.t)}</div>${r('Kategori',p.kt)}${r('Tanggal terbit',p.tg)}${r('Status',p.st)}${r('Ukuran file',p.fs)}${r('Dilihat',p.vw?String(p.vw).replace(/\B(?=(\d{3})+(?!\d))/g,'.')+' kali':'')}<div class="kt">Keterangan</div><div class="kd">${esc(p.d).replace(/\n\n/g,'<br><br>')}</div>${p.pdf?`<button class="pv" data-src="${p.pdf}">📄 Pratinjau isi dokumen</button><div class="pw"></div>`:''}<div class="sm">Sumber: <a href="${p.u}" target="_blank" rel="noopener noreferrer">${esc(p.u.replace('https://',''))}</a></div></div>`}).join('')+
    `<p style="opacity:.75;font-size:13px">Daftar lengkap: <a href="https://binamarga.pu.go.id/index.php/nspk/pedoman-teknis-bidang-jt" target="_blank" rel="noopener noreferrer">Pedoman Jembatan & Terowongan</a> · <a href="https://binamarga.pu.go.id/index.php/nspk/pedoman-teknis-bidang-jalan" target="_blank" rel="noopener noreferrer">Pedoman Jalan</a> · <a href="https://binamarga.pu.go.id/index.php/nspk/rekap" target="_blank" rel="noopener noreferrer">Rekap NSPK</a></p>`};
  i.oninput=list;list()}
pk.querySelector('.x').onclick=()=>{pk.style.display='none';pk.querySelector('#pkb').innerHTML=''};
mk('📚 Pustaka',()=>{if(pk.style.display==='flex'){pk.querySelector('.x').onclick();return}pk.style.display='flex';ai.style.display='none';drawPk()});
